apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ljfy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qwhu-tenant/rhtap-demo-app/hacbs-test-project-ljfy@sha256:cef3a14df99667255fd33e1cc3b7c32603602eca75697a37361c385fb609dbf6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
